import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cash Moves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Cash Moves
        </h1>

        <p className={styles.description}>
          Get started by choosing your level of experiece
        </p>  
        <div className={styles.grid}>
          <button> Beginer</button>
          <button> Expert</button>
          
        </div>


        <div className={styles.grid}>
      <li>
           <button>My Balace &rarr;</button> 
            <p>$0</p>
    

            <button>Learn &rarr; </button>
            <p> Learn about Cash Moves in an interactive course with quizzes! </p>

            <button>Predictor &rarr;</button>
            <p> Discover and deploy predictor example.</p>
      </li>
        </div>
      </main>

      <footer className={styles.footer}>
        
          Powered by{' '}
         <p> Cash Moves </p>
      </footer>
    </div>
  )
}
